### ISSUE TITLE
Why `INTER_LINEAR` instead of `INTER_AREA` for resizing

### ISSUE THREAD

**Issue by chicn** [AlphaQi/MTCNN-light#11]
## What

Since you use `INTER_LINEAR` for resizing images in mtcnn,
I'd be happy if I could hear why not `INTER_AREA` from you.

If you have no policy for this interpolation, that will also be the enough answer to me!

Thanks in advance!!

**Comment by chicn** [comment]
^ @AlphaQi Please could you answer this?

**Comment by AlphaQi** [comment]
I am sorry, I am busy with campus recruitment last month.
the answer is , INTER_LINEAR is 4 times faster than INTER_AREA, the effect of two methods is small.

**Comment by chicn** [comment]
@AlphaQi Thank you!! I appreciate your answer.
