### ISSUE TITLE
would you like to provide the code to convert the caffemodel to txt file?

### ISSUE THREAD

**Issue by imistyrain** [AlphaQi/MTCNN-light#2]

**Comment by AlphaQi** [comment]
Sorry, I'm a little busy lately , and I think the code convert caffemodel is not difficult.

**Comment by inlmouse** [comment]
@AlphaQi Did your txt files convert from the official version caffemodel(Kaipeng Zhang's)? I tried to convert a txt file from Zhang's model, however, it seems different from the model you provide.

**Comment by Devy001** [comment]
@AlphaQi can you share the method of converting caffemodel to your txt ?  I want to convert my trained caffemodel to your txt, thank you.

**Comment by githublet** [comment]
> @AlphaQi can you share the method of converting caffemodel to your txt ? I want to convert my trained caffemodel to your txt, thank you.

https://github.com/githublet/mtcnn/blob/master/caffemodel2txt/caffemodel2txt.py
